import { FC } from 'react';

interface DiagnosticInsightsProps {
  differentialDiagnoses: string[];
  redFlags: string[];
  recommendedTests?: string[];
}

const DiagnosticInsights: FC<DiagnosticInsightsProps> = ({ 
  differentialDiagnoses, 
  redFlags,
  recommendedTests = []
}) => {
  return (
    <div className="bg-white dark:bg-zinc-900 rounded-lg shadow-md overflow-hidden">
      <div className="bg-gradient-to-r from-blue-100 to-indigo-100 dark:from-blue-900/40 dark:to-indigo-900/40 px-4 py-3">
        <h3 className="font-semibold text-blue-800 dark:text-blue-300 flex items-center">
          <span className="material-icons mr-2">psychology</span>
          AI Diagnostic Insights
        </h3>
      </div>
      
      <div className="p-4 divide-y divide-gray-200 dark:divide-zinc-700">
        {/* Differential Diagnoses Section */}
        <div className="pb-3">
          <h4 className="font-medium text-neutral-700 dark:text-zinc-300 flex items-center mb-2">
            <span className="material-icons text-blue-600 dark:text-blue-400 mr-1 text-sm">radar</span>
            Possible Conditions to Consider
          </h4>
          
          {differentialDiagnoses.length > 0 ? (
            <ul className="space-y-1 pl-7 list-disc">
              {differentialDiagnoses.map((diagnosis, index) => (
                <li key={index} className="text-sm text-neutral-600 dark:text-zinc-400">
                  {diagnosis}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-neutral-500 dark:text-zinc-500 italic">
              Not enough data to generate differential diagnoses
            </p>
          )}
          
          <p className="text-xs text-neutral-500 dark:text-zinc-500 mt-2 italic">
            Note: These are potential conditions based on reported symptoms and are not definitive diagnoses.
          </p>
        </div>
        
        {/* Red Flags Section */}
        <div className="py-3">
          <h4 className="font-medium text-red-600 dark:text-red-400 flex items-center mb-2">
            <span className="material-icons mr-1 text-sm">warning</span>
            Critical Concerns
          </h4>
          
          {redFlags.length > 0 ? (
            <ul className="space-y-1">
              {redFlags.map((flag, index) => (
                <li key={index} className="flex items-start">
                  <span className="material-icons text-red-600 dark:text-red-400 mr-1 text-sm">priority_high</span>
                  <span className="text-sm text-neutral-700 dark:text-zinc-300">{flag}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-neutral-500 dark:text-zinc-500 italic">
              No critical concerns detected at this time
            </p>
          )}
        </div>
        
        {/* Recommended Tests Section (if provided) */}
        {recommendedTests.length > 0 && (
          <div className="pt-3">
            <h4 className="font-medium text-neutral-700 dark:text-zinc-300 flex items-center mb-2">
              <span className="material-icons mr-1 text-sm">science</span>
              Recommended Tests
            </h4>
            
            <ul className="space-y-1 pl-7 list-disc">
              {recommendedTests.map((test, index) => (
                <li key={index} className="text-sm text-neutral-600 dark:text-zinc-400">
                  {test}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
      
      <div className="bg-blue-50 dark:bg-blue-900/20 px-4 py-2 border-t border-blue-100 dark:border-blue-900/50">
        <p className="text-xs text-blue-600 dark:text-blue-400">
          <span className="font-medium">Medical Disclaimer:</span> This information is generated by an AI system and should not replace professional medical advice. Always consult with a healthcare provider for diagnosis and treatment.
        </p>
      </div>
    </div>
  );
};

export default DiagnosticInsights;